ALTER TABLE IF EXISTS public.mindex_filtered_commodities_df
    ADD COLUMN "TITLE" VARCHAR(70),
	ADD COLUMN "SUB_TYPE" VARCHAR(30),
	ADD COLUMN "STAGE" VARCHAR(25),
	ADD COLUMN "PROJECT_TITLE" VARCHAR(70),
	ADD COLUMN "LONGITUDE" double precision,
	ADD COLUMN "LATITUDE" double precision,
	ADD COLUMN "COMMODITIES" VARCHAR(40),
	ADD COLUMN "COMMODITY_GROUP_NAME" VARCHAR(30),
	ADD COLUMN "TARGET_GROUP_NAME" VARCHAR(30),
	ADD COLUMN "LGA_NAME" VARCHAR(70),
	ADD COLUMN "DISTRICT_NAME" VARCHAR(30),
	ADD COLUMN "TECTONIC_UNIT" VARCHAR(70);


SELECT *
FROM mindex_filtered_commodities_df;